import Head from 'next/head'
import Banner from '../components/banner/banner';
import Navbar from '../components/nav/navbar';
import SectionCards from '../components/Card/section-cards';
import styles from '../styles/Home.module.css';

import { getVideos } from '../lib/videos';

export async function getServerSideProps() {
  const disneyVideos = getVideos();

  return { props: { disneyVideos } }
};

export default function Home({ disneyVideos }) {
  console.log({ disneyVideos })
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"   />
      </Head>

      <Navbar username="thisisboa@working.com" />

      <Banner 
        title='Chingu the Black dog'
        subTitle='a very cute dog'
        imgUrl='/static/chingu.webp'
        />

      <div className={styles.sectionWrapper}>
        <SectionCards 
        title='Disney'
        videos={disneyVideos}
        size="large"
        /> 
      </div>
      <div className={styles.sectionWrapper}>
        <SectionCards 
        title='Disney'
        videos={disneyVideos}
        size="large"
        /> 
      </div>
    </div>
  );
}
