import Head from 'next/head'
import Banner from '../components/banner/banner';
import Navbar from '../components/banner/nav/nav';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"   />
      </Head>

      <Navbar username="boa@gmail.com" />
      {/* <Card /> */}
      <Banner 
        title='Chingu the Black dog'
        subTitle='a very cute dog'
        imgUrl='/static/chingu.webp'
        />
      
    </div>
  );
}
