import Head from 'next/head'
import Banner from '../components/banner/banner';
import Navbar from '../components/nav/navbar';
import Card from '../components/card/card';
import SectionCards from '../components/Card/section-cards';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"   />
      </Head>

      <Navbar username="boa@gmail.com" />

      <Banner 
        title='Chingu the Black dog'
        subTitle='a very cute dog'
        imgUrl='/static/chingu.webp'
        />
      <div className={styles.sectionWrapper}>
        <SectionCards title='Disney' />  
      </div>
    </div>
  );
}
